# Generated by Django 5.1.7 on 2025-11-14 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station_type', models.CharField(choices=[('BEBIDAS_CALIENTES', 'Bebidas Calientes'), ('BEBIDAS_FRIAS', 'Bebidas Frías'), ('PANADERIA', 'Panadería'), ('COCINA', 'Cocina Principal'), ('POSTRES', 'Postres')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('can_handle_categories', models.JSONField(default=list, help_text="Lista de category_types que puede manejar: ['BEBIDAS', 'POSTRES']")),
            ],
            options={
                'verbose_name': 'Estación de Cocina',
                'verbose_name_plural': 'Estaciones de Cocina',
                'db_table': 'kitchen_stations',
            },
        ),
        migrations.CreateModel(
            name='StationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='kitchen.kitchenstation')),
            ],
            options={
                'verbose_name': 'Cola de Estación',
                'verbose_name_plural': 'Colas de Estaciones',
                'db_table': 'station_queue',
                'ordering': ['assigned_at'],
            },
        ),
    ]
